---
title: "Correlator"
author: "Gab"
date: "16/01/2021"
output: html_document
---

### Correlation
Ce code récupère 4 fichiers (calendrier, Meteo, RATP, PollutionExt) et génère 1 fichier avec l'ensemble des colonnes
La correlation est basée la référence de temps, nomé 'timestamp', et de class POSIX.


```{r}
library(jsonlite) #inutile
library(tidyverse)
```


#Définition des fichiers sources
```{r}
# ce code est sous ./Code/Preparation des donnees/
# et les fichiers à traiter son sous ./Data/Prepared/

fichierPolExt <- "../../Data/Prepared/PollutionExterieure3.csv"
fichierRATP <- "../../Data/Prepared/RATP_qair_2013_2020_Prep2.csv"
fichierMeteo <- "../../Data/Prepared/meteo_interpole2.csv"
fichierCalendrier <- "../../Data/Prepared/calendrier2.csv"

```


#Ajout des colonnes sur un Tibble final
```{r}
#le fichier calendrier sert de base sur laquelle seront ajoutées les colonnes des fichiers RATP, Météo et PollutionExterne
dfFinal <- read_csv(fichierCalendrier)

dfMeteo <- read_csv(fichierMeteo)
dfFinal <- left_join(dfFinal, dfMeteo, by="Timestamp")
rm(dfMeteo)

dfRATP <- read_csv(fichierRATP)
dfFinal <- left_join(dfFinal, dfRATP, by="Timestamp")
rm(dfRATP)

dfPolExt <- read_csv(fichierPolExt)
dfFinal <- left_join(dfFinal, dfPolExt, by="Timestamp")
rm(dfPolExt)

### savegarde du résultat dans un fichier
write_csv(dfFinal, "../../Data/Prepared/DataCorrelated.csv")
```

