---
title: "meteo"
author: "Dimitri"
date: "05/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r warning=FALSE}
library(jsonlite)
library(plyr)
library(data.table)
library(tidyverse)
library(corrplot)
path_2_write = "C:/Users/A56814/Documents/Projet Data Science/metroqualitedelair-main/Data/"
file_2_write = "meteo_2013_2019.csv"
file_meteo   = paste(path_2_write,file_2_write,sep="")

df <- fread(file_meteo)
df <- data.frame(df)
summary(df)

# Calculer les NA
valNA <- sapply(df,function(x) sum(is.na(x)))
txNA  <- valNA / nrow(df)*100
valsup50 <- names(txNA)[txNA > 50]
df <- df[,-which(colnames(df)  %in% valsup50)]

df <- df[,!colnames(df) %in% c("ht_neige", "type_de_tendance_barometrique", "mois_de_l_annee", "ssfrai", "perssfrai", "vv",
             "altitude", "w2", "w1", "pmer", "per", "t", "etat_sol")]  # Suppression variables non pertinentes ou redondantes (Exemple t en Kelvin versus t en Celsius)
valnumeric <- sapply(df,function(x) is.numeric(x))
numvalue   <- names(valnumeric[valnumeric==TRUE])
mcor <- cor(df[,colnames(df) %in% numvalue], use = "complete.obs")
write.table(mcor, paste(path_2_write,"mcor.csv",sep=""), sep = ";")

corrplot(mcor, type="upper", order="hclust", tl.col="black", tl.srt=45)
View(mcor)


# on repasse les NA pour garder les mieux remplis sur les corrélées
valNA <- sapply(df,function(x) sum(is.na(x)))
txNA  <- valNA / nrow(df)*100

# td et tc corrélés on garde tc température plutot que point de rosée
# tc et u corrélés on garde tc température plutot que humidité
# cod_tend et tend + tend24 corrélés on garde cod_tend type de tendance barométrique, moins de modalités et idem en NA
# hnuage1 corrélé avec hbas cl ctype1 on garde cl 

# On renettoye pour y voir plus clair
df <- df[,!colnames(df) %in% c("td", "u", "tend", "tend24", "hnuage1", "hbas", "ctype1")]
numvalue   <- names(valnumeric[valnumeric==TRUE])
mcor <- cor(df[,colnames(df) %in% numvalue], use = "complete.obs")
corrplot(mcor, type="upper", order="hclust", tl.col="black", tl.srt=45)

# on repasse les NA pour garder les mieux remplis sur les corrélées
valNA <- sapply(df,function(x) sum(is.na(x)))
txNA  <- valNA / nrow(df)*100


# nnuage1 et n corrélés on garde n nébulosité totale avec moins de NA
# n et nbas corrélés on garde n nébulosité totale 
# ww corrélé avec cl cm et ch on garde ww temps présent avec moins de NA
# rr1 corrélé avec rr3 rr6 rr12 et rr24 on garde rr3 précipitations 3 dernieres heures avec moins de NA
# rafper corrélé avec ff et raf10 on garde ff vitesse vent moyen
# on peut aussi enlever temps_passe_1 car 5% de NA et en lien avec variable temps_present

# On renettoye pour y voir plus clair
df <- df[,!colnames(df) %in% c("nnuage1", "nbas", "cl", "cm", "ch", "rr1", "rr6", "rr12", "rr24", "rafper", "raf10", "temps_passe_1")]
numvalue   <- names(valnumeric[valnumeric==TRUE])
mcor <- cor(df[,colnames(df) %in% numvalue], use = "complete.obs")
corrplot(mcor, type="upper", order="hclust", tl.col="black", tl.srt=45)


show_var_missing_values<-function(var_name,printTOrPlotF=TRUE)
  
{    
  nulls_per_year_month<-table(df[is.na(df[var_name]),colnames(df)[9]] %>% substr(1,7))
  #Aide4 : Il faut choisir une option parce que les deux ne marche pas
  if (printTOrPlotF==TRUE)
  {
    print(var_name)
    print(nulls_per_year_month)
  }
  else
  {
    plot(nulls_per_year_month,main=var_name,type="l")
  }
}

for (col_var in colnames(df)[-9])
{
  show_var_missing_values(col_var)
}
#plot
for (col_var in colnames(df)[-9])
{
  show_var_missing_values(col_var,FALSE)
}

```
```{r }
## 10 Variables restantes

# rr3 : précipitations dans les 3 dernières heures
# temps_present : temps actuel
# tc : température en Celsius
# pres : pression station
# dd : direction du vent moyen 10mn
# ww : temps présent
# cod_tend : type de tendance barométrique
# ff : vitesse du vent moyen 10mn
# date : la date toutes les heures
# n : nébulosité totale

head(df)
summary(df)
```
